computer_name = `networksetup -getcomputername`.chomp

# The work sudo policy blocks mas installs and upgrades
unless ["7385-Y3FH97X-MAC", "MULO-JQ97NW-MBP"].include?(computer_name)
  mas "Amphetamine", id: 937984704
end
