# see: https://starship.rs/config/
# see: https://starship.rs/presets/nerd-font.html

# Avoid a newline at the top of the shell (handled by my preexec and precmd functions)
add_newline = false

# see: https://starship.rs/config/#prompt
format = """
$directory\
$cmd_duration\
$character\
"""

# see: https://starship.rs/advanced-config/#enable-right-prompt
right_format = """
$git_branch\
$kubernetes\
$gcloud\
$nodejs\
$python\
$all\
"""

[aws]
  symbol = "  "

[buf]
  symbol = " "

[c]
  symbol = " "

[conda]
  symbol = " "

[crystal]
  symbol = " "

[dart]
  symbol = " "

[directory]
  read_only = " 󰌾"
  style = "#B4BEFE bold"
  truncate_to_repo = true
  truncation_length = 3

[docker_context]
  disabled = true
  symbol = " "

[elixir]
  symbol = " "

[elm]
  symbol = " "

[fennel]
  symbol = " "

# Keep left/right prompt on same line while adding a newline for the prompt input:
# https://starship.rs/config/#fill
# https://www.youtube.com/watch?v=VgTu1_92U0U
[fill]
  symbol = " "

[fossil_branch]
  symbol = " "

[gcloud]
  detect_env_vars = ['GOOGLE_CLOUD_PROJECT']
  disabled = true
  format = '  [$symbol$project]($style)'
  symbol = ''
  # symbol = '󰅟  '
  # symbol = "  "

[gcloud.project_aliases]
  eng-infrastructure = 'eng-infra'
  rp006-prod-49a893d8 = 'rp006-prod'

[gcloud.region_aliases]
  asia-northeast1 = 'an1'
  us-central1 = 'uc1'

[git_branch]
  format = '[$symbol$branch]($style)'
  symbol = ""
  # symbol = " "
  # style = "bright-black"

[git_status]
  disabled = true

[golang]
  format = '  [$symbol$version]($style)'
  symbol = ''
  # symbol = " "
  version_format = "${raw}"

[guix_shell]
  symbol = " "

[haskell]
  symbol = " "

[haxe]
  symbol = " "

[hg_branch]
  symbol = " "

[hostname]
  ssh_symbol = " "

[java]
  symbol = " "

[julia]
  symbol = " "

[kotlin]
  symbol = " "

[kubernetes]
  detect_files = ['Dockerfile', 'Kubernetesfile', 'docker-compose.yml', 'helmfile.yaml']
  # detect_folders = ['k8s', '.k8s', 'k8s-config', '.k8s-config', 'deploy', '.deploy']
  disabled = false
  format = '  [$context$symbol$namespace]($style)'
  symbol = ':'                                     # gaming the intended use of "symbol" here so I can remove the colon when namespace is irrelevant
  # symbol = '☸ '

[[kubernetes.contexts]]
  context_pattern = 'docker-desktop'
  symbol = ''

[[kubernetes.contexts]]
  context_alias = 'principal'
  context_pattern = 'gke_eng-infrastructure_us-east1_principal'

[[kubernetes.contexts]]
  context_alias = 'prod-cluster'
  context_pattern = 'gke_prod-cluster-cc74bd08_us-central1_prod-cluster'

[[kubernetes.contexts]]
  context_alias = 'rp006-prod'
  context_pattern = 'gke_rp006-prod-49a893d8_us-central1_rp006-prod'

[lua]
  disabled = true
  symbol = " "

[memory_usage]
  symbol = "󰍛 "

[meson]
  symbol = "󰔷 "

[nim]
  symbol = "󰆥 "

[nix_shell]
  symbol = " "

[nodejs]
  format = '  [$symbol$version]($style)'
  style = 'bold green'
  symbol = ""
  # symbol = " "
  version_format = "${raw}"

[ocaml]
  symbol = " "

[os.symbols]
  Alpaquita = " "
  Alpine = " "
  Amazon = " "
  Android = " "
  Arch = " "
  Artix = " "
  CentOS = " "
  Debian = " "
  DragonFly = " "
  Emscripten = " "
  EndeavourOS = " "
  Fedora = " "
  FreeBSD = " "
  Garuda = "󰛓 "
  Gentoo = " "
  HardenedBSD = "󰞌 "
  Illumos = "󰈸 "
  Linux = " "
  Mabox = " "
  Macos = " "
  Manjaro = " "
  Mariner = " "
  MidnightBSD = " "
  Mint = " "
  NetBSD = " "
  NixOS = " "
  OpenBSD = "󰈺 "
  OracleLinux = "󰌷 "
  Pop = " "
  Raspbian = " "
  RedHatEnterprise = " "
  Redhat = " "
  Redox = "󰀘 "
  SUSE = " "
  Solus = "󰠳 "
  Ubuntu = " "
  Unknown = " "
  Windows = "󰍲 "
  openSUSE = " "

[package]
  disabled = true
  symbol = "󰏗 "

[perl]
  symbol = " "

[php]
  symbol = " "

[pijul_channel]
  symbol = " "

[python]
  # detect_extensions = []
  # detect_files=[]
  format = '  [${symbol}(${version})( \($virtualenv\))]($style)'
  symbol = ""
  # symbol = "  "
  version_format = "${raw}"

[rlang]
  symbol = "󰟔 "

[ruby]
  symbol = " "

[rust]
  symbol = " "

[scala]
  symbol = " "

[swift]
  symbol = " "

[zig]
  symbol = " "
