# NOTE: ruby works in this file, so feel free to use it for conditional logic, etc
# see: https://github.com/Homebrew/homebrew-bundle

# Execute the `networksetup` command in a subshell and remove the trailing '\n'
computer_name = `networksetup -getcomputername`.chomp

########
# TAPS #
########

tap "buo/cask-upgrade" # see: https://gist.github.com/ChristopherA/a579274536aab36ea9966f301ff14f3f#best-practices-brew-cask-mas-and-cu
tap "jesseduffield/lazydocker"

############
# PACKAGES #
############

brew "bash"
brew "bats-core" # for bash testing
brew "coreutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta" # for git: https://dandavison.github.io/delta/
brew "github-keygen" # for git ssh
brew "go"
brew "goose" # for go
brew "httpie"
brew "imagemagick" # for kitty's icat image support
brew "jq" # for parsing json
brew "kubectl" # for kubernetes
brew "kubectx" # for kubernetes
brew "jesseduffield/lazydocker/lazydocker"
brew "lazygit"
brew "mas"
brew "m-cli" # macos CLI: https://github.com/rgcr/m-cli
brew "postgresql@14"
brew "libpq" # for postgres
brew "powerlevel10k"
brew "speedtest-cli"
brew "stern" # for kubectl
brew "svn" # for font cask installations

if computer_name == "Air"
  brew "deno"
  brew "gleam"
  brew "zig"
end

if computer_name == "7385-Y3FH97X-MAC" || computer_name == "MULO-JQ97NW-MBP"
  brew "helm" # for kubernetes
  brew "kafka"
  brew "librdkafka" # for kafka
  brew "lzlib"
  brew "opa"
  brew "openjdk" # for java
  brew "redis"
  brew "tcl-tk"
  brew "zlib"
end

#########
# FONTS #
#########

# Fonts
# see: https://github.com/Homebrew/homebrew-cask/tree/master/Casks/font
cask "font-symbols-only-nerd-font"
cask "font-ubuntu-mono"
cask "font-ubuntu-mono-nerd-font"

################
# APPS (CASKS) #
################

cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "brave-browser"
# NOTE: don't install "docker" cask until Apple Silicon issues resolved
cask "firefox"
cask "ghostty"
cask "hyperkey" # karabiner become impossible to allow on work laptop...
cask "kitty"
cask "neohtop" # see: https://abdenasser.github.io/neohtop/
cask "notion"
cask "obsidian"
cask "raycast"
cask "rectangle"
cask "sip-app"
cask "thingsmacsandboxhelper" # enables Things 3 "Quick Entry with Autofill" feature: https://formulae.brew.sh/cask/thingsmacsandboxhelper
cask "vlc"
cask "zed"

if computer_name == "Air"
  cask "1password"
  cask "google-chrome" # NOTE: work likely controls installation of this app
  # NOTE: manually download prepros v6 instead (just need it for Adam's site)
  # cask "transmit
  cask "zoom" # NOTE: work likely controls installation of this app
end

if computer_name == "Mini"
  cask "1password"
  cask "backblaze"
  cask "carbon-copy-cloner"
  # cask "handbrake"
end

if computer_name == "7385-Y3FH97X-MAC" || computer_name == "MULO-JQ97NW-MBP"
  cask "meetingbar" # for auto-joining zoom calls
end

########################
# APPS (MAC APP STORE) #
########################

if computer_name != "Mini"
  # FIXME: feedbin id not found
  # mas "Feedbin", id: 1444961766 # required for the Safari extension
  mas "Notion Web Clipper", id: 1559269364 # Safari extension
  mas "Reeder 5.", id: 1529448980
  mas "Things 3", id: 904280696
end

mas "Amphetamine", id: 937984704

message = "\📦 Loading additional Mac App Store apps for #{computer_name}\n"

if computer_name == "Air"
  # mas "Bear", id: 1091189122
  mas "Keynote", id: 409183694
  mas "Numbers", id: 409203825
  mas "Pages", id: 409201541
end
