require('mu.plugins-setup') -- should be first
require('mu.core.colorscheme')
require('mu.core.keymaps')
require('mu.core.options')
require('mu.plugins.comment')
require('mu.plugins.lsp.mason')
require('mu.plugins.lualine')
require('mu.plugins.nvim-cmp')
require('mu.plugins.nvim-tree')
require('mu.plugins.telescope')
