k9s:
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /var/folders/14/gdbl0cfn09d5mz9js76lfkq04jxnfc/T/k9s-screens-michael.uloth
  ui:
    skin: catppuccin-mocha-transparent
