#!/usr/bin/env bash
set -euo pipefail

source "${DOTFILES}/tools/bash/utils.bash"

output="${DOTFILES}/tools/homebrew/Brewfile.generated"

mapfile -t brewfiles < <(
  find "${DOTFILES}/tools" -maxdepth 2 -name "Brewfile" \
    ! -name "Brewfile.generated" \
    ! -name "Brewfile.legacy" \
    ! -path "*/@new/*" \
    ! -path "*/@archive/*" |
    sort
)

mkdir -p "$(dirname "$output")"
printf "# Auto-generated by generate-brewfile.bash — do not edit directly\n\n" >"$output"

for f in "${brewfiles[@]}"; do
  tool="$(basename "$(dirname "$f")")"
  {
    printf "# --- %s ---\n" "$tool"
    cat "$f"
    printf "\n"
  } >>"$output"
done

debug "✅ Generated combined Brewfile from ${#brewfiles[@]} tool Brewfiles"
