# see: https://github.com/Homebrew/homebrew-bundle

# TODO: make Brewfile.common + Brewfile.work + Brewfile.personal + Brewfile.mini?
# WARN: Don't add work-only packages here! Treat them as one-off installs on my work laptop.

# Taps (to avoid warnings when installing from custom taps below)
tap "arl/arl" # for gitmux
tap "hashicorp/tap" # for terraform
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"
tap "saulpw/vd" # for visidata
tap "yqrashawn/goku" # for karabiner

# Packages
brew "bat" # replaces cat
brew "btop" # top alternative
brew "commitizen" # for git
brew "coreutils"
brew "ctop" # for docker
brew "eza" # replaces ls
brew "fd" # replaces find; used by yazi
brew "ffmpegthumbnailer" # for yazi
brew "fnm" # replaces nvm
brew "fzf" # awesome; used by yazi
brew "gh"
brew "git"
brew "arl/arl/gitmux" # for tmux
brew "glances" # top alternative
brew "gnu-sed"
brew "go"
brew "yqrashawn/goku/goku" # for karibiner
brew "goose" # for go
brew "hadolint" # for docker
brew "htop" # top alternative
brew "imagemagick" # for kitty's icat image support
brew "jq" # for parsing json; used by yazi
brew "kubectl" # for kubernetes
brew "jesseduffield/lazydocker/lazydocker"
brew "jesseduffield/lazygit/lazygit"
brew "mas"
brew "neovim"
brew "poppler" # for yazi
brew "postgresql@14"
brew "powerlevel10k"
brew "pyenv" # manages python versions
brew "pyenv-virtualenv" # allow pyenv to manage virtualenvs
brew "ripgrep" # for telescope, yazi
brew "saulpw/vd/visidata"
brew "starship"
brew "stern" # for kubectl
brew "stylua" # for lua
brew "svn" # for font cask installations
brew "taplo" # for toml
brew "hashicorp/tap/terraform" # for neovim + vs code
brew "tidy-html5" # for linting html + xml in neovim
brew "tmux"
brew "trash"
brew "tree"
brew "unar" # for yazi
brew "vifm"
brew "wget" # for neovim
brew "yazi" # terminal file manager
brew "zoxide" # for yazi
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Apps
cask "1password-cli"
cask "alfred"
cask "appcleaner"
# cask "backblaze"
cask "brave-browser"
cask "firefox"
# cask "google-chrome" NOTE: work may control this app
# cask "handbrake"
cask "hyperkey"
# cask "ishowu-instant"
cask "karabiner-elements"
cask "kitty"
cask "notion"
cask "obsidian"
# cask "prepros" NOTE: manually download v6 instead (just need it for Adam's site)
cask "raycast"
cask "rectangle"
cask "runjs"
# cask "transmit"
cask "visual-studio-code"
cask "vlc"
# cask "zoom" NOTE: work may control this app

# Fonts
# see: https://github.com/Homebrew/homebrew-cask/tree/master/Casks/font
cask "font-symbols-only-nerd-font" # for yazi
cask "font-ubuntu-mono"
cask "font-ubuntu-mono-nerd-font"

# macOS App Store
mas "Amphetamine", id: 937984704
# mas "Bear", id: 1091189122
# mas "Contrast", id: 1254981365
# mas "Fantastical - Calendar", id: 975937182
mas "Keynote", id: 409183694
mas "Notion Web Clipper", id: 1559269364 # Safari extension
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
# mas "PiPifier", id: 1160374471
# mas "Pixave", id: 924891282
# mas "Pixelmator Pro", id: 1289583905
mas "Reeder 5.", id: 1529448980
mas "Sip", id: 507257563
# mas "Smart Converter Pro", id: 450078312
# mas "Spark", id: 1176895641
mas "Things 3", id: 904280696
mas "Vimari", id: 1480933944

# VS Code
# TODO: set IS_WORK_LAPTOP in setup.zsh (may need to prompt for y/N)
# TODO: if system "$IS_WORK_LAPTOP"
# TODO: if system "! $IS_WORK_LAPTOP"
vscode "astro-build.astro-vscode"
vscode "austenc.tailwind-docs"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "cweijan.vscode-database-client2"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "equinusocio.vsc-material-theme"
vscode "equinusocio.vsc-material-theme-icons"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-rename-tag"
vscode "ginfuru.better-nunjucks"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "hashicorp.terraform"
vscode "hoovercj.vscode-settings-cycler"
vscode "jdinhlife.gruvbox"
vscode "malmaud.tmux"
vscode "mattpocock.ts-error-translator"
vscode "mechatroner.rainbow-csv"
vscode "mgmcdermott.vscode-language-babel"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.test-adapter-converter"
vscode "patbenatar.advanced-new-file"
vscode "rangav.vscode-thunder-client"
vscode "redhat.vscode-yaml"
vscode "richie5um2.vscode-sort-json"
vscode "rust-lang.rust-analyzer"
vscode "sidneys1.gitconfig"
vscode "sleistner.vscode-fileutils"
vscode "sumneko.lua"
vscode "tamasfe.even-better-toml"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.errorlens"
vscode "vitest.explorer"
vscode "vivaxy.vscode-conventional-commits"
vscode "vscodevim.vim"
vscode "vspacecode.whichkey"
vscode "wayou.vscode-todo-highlight"
vscode "wooodhead.vscode-wrap-console-log-simple"
vscode "xadillax.viml"
vscode "yzhang.markdown-all-in-one"