# see: https://k9scli.io/topics/config/

k9s:
  cluster: gke_eng-infrastructure_us-east1_principal
  featureGates:
    # see: https://k9scli.io/topics/shell/
    nodeShell: true # enable node shell feature
  namespace:
    active: phenomap
    lockFavorites: false
    favorites:
      - phenomap
  portForwardAddress: localhost
  view:
    active: dp
