# TODO: move to separate tool folders?
brew "bat" # replaces cat
brew "bottom" # top alternative
brew "btop" # top alternative
brew "fd" # replaces find
brew "gnu-sed"
brew "ripgrep" # for telescope
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

