# taps
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

# packages
# brew "bat"
brew "exa"
brew "fzf"
brew "gh"
# brew "git"
# brew "lazygit"
brew "mas"
brew "neovim"
brew "pyenv"
brew "pyenv-virtualenv"
# brew "ranger"
# brew "ripgrep"
brew "fnm"
brew "shellcheck"
# brew "speedtest-cli"
brew "starship"
brew "svn"            # required for font cask installations
# brew "tldr"
brew "tmux"
brew "vifm"
# brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Applications
cask "alfred"
# cask "appcleaner"
cask "backblaze"
cask "cleanmymac"
# cask "discord"
cask "drivedx"
cask "gitkraken"
# cask "handbrake"
cask "ishowu-instant"
# cask "karabiner-elements"
cask "keybase"
cask "kitty"
# cask "local"
cask "microsoft-teams"
cask "notion"
cask "openvpn-connect"
cask "prepros"
cask "rectangle"
cask "runjs"
# cask "sizzy"
# cask "skype"
cask "transmit"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

# Browsers
cask "brave-browser"
cask "firefox"
cask "google-chrome"

# Fonts
cask "font-ubuntu-mono"
cask "font-ubuntu-mono-nerd-font"

# macOS App Store
mas "1Password 7", id: 1333542190
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
# mas "Contrast", id: 1254981365
mas "Fantastical - Calendar", id: 975937182
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
# mas "PiPifier", id: 1160374471
mas "Pixave", id: 924891282
mas "Pixelmator Pro", id: 1289583905
mas "Reeder 5.", id: 1529448980
mas "Slack", id: 803453959
mas "Sip", id: 507257563
# mas "Smart Converter Pro", id: 450078312
mas "Spark", id: 1176895641
mas "Things 3", id: 904280696
mas "Vimari", id: 1480933944

