# Don't add work-only packages here! Treat them as one-off installs on my work laptop.

# Taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "arl/arl" # for gitmux
tap "goku" # for goku
tap "hashicorp/tap" # for terraform
tap "jesseduffield/lazygit"
tap "jesseduffield/lazydocker"

# Packages
brew "bat"
brew "eza"
brew "fd"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "gitmux"
brew "gnu-sed"
brew "goku" # for karibiner
brew "hashicorp/tap/terraform"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "neovim"
brew "powerlevel10k"
brew "ripgrep" # for telescope
brew "starship"
brew "stylua"
brew "svn" # for font cask installations
brew "tmux"
brew "trash"
brew "vifm"
brew "wget" # for neovim
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Apps
cask "alfred"
cask "appcleaner"
# cask "backblaze"
cask "brave-browser"
# cask "cleanmymac"
cask "firefox"
# cask "google-chrome"
# cask "handbrake"
cask "hyperkey"
# cask "ishowu-instant"
cask "karabiner-elements"
cask "kitty"
cask "notion"
cask "obsidian"
# cask "prepros" - manually download v6 instead
cask "raycast"
cask "rectangle"
cask "runjs"
# cask "transmit"
cask "visual-studio-code"
cask "vlc"
# cask "warp"
cask "wezterm"
# cask "zoom"

# Fonts
cask "font-ubuntu-mono"
cask "font-ubuntu-mono-nerd-font"

# macOS App Store
mas "Amphetamine", id: 937984704
# mas "Bear", id: 1091189122
# mas "Contrast", id: 1254981365
# mas "Fantastical - Calendar", id: 975937182
mas "Keynote", id: 409183694
mas "Notion Web Clipper", id: 1559269364 # Safari extension
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
# mas "PiPifier", id: 1160374471
# mas "Pixave", id: 924891282
# mas "Pixelmator Pro", id: 1289583905
mas "Reeder 5.", id: 1529448980
mas "Sip", id: 507257563
# mas "Smart Converter Pro", id: 450078312
# mas "Spark", id: 1176895641
mas "Things 3", id: 904280696
mas "Vimari", id: 1480933944

