return {
  -- {
  --   'nvimtools/none-ls.nvim',
  --   keys = {
  --     {
  --       '<leader>xtp',
  --       function()
  --         -- see: https://github.com/jose-elias-alvarez/null-ls.nvim/discussions/1258#discussioncomment-4245688
  --         require('null-ls').toggle('prettier')
  --       end,
  --       desc = 'Toggle prettier',
  --     },
  --   },
  --   opts = function() -- replace all default opts
  --     local nls = require('null-ls')
  --     return {
  --       -- root_dir = require('null-ls.utils').root_pattern('package.json', '.git'),
  --       -- formatters & linters mason will automatically install + set up below
  --       -- see: https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#code-actions
  --       sources = {
  --         nls.builtins.code_actions.proselint,
  --         nls.builtins.code_actions.shellcheck, -- bash linter
  --
  --         -- see: https://github.com/jose-elias-alvarez/typescript.nvim#setup-1
  --         require('typescript.extensions.null-ls.code-actions'),
  --
  --         nls.builtins.diagnostics.flake8, -- python linter
  --         nls.builtins.diagnostics.mypy, -- python type-checker
  --         nls.builtins.diagnostics.puglint, -- pug linter
  --         nls.builtins.diagnostics.shellcheck, -- bash linter
  --         nls.builtins.diagnostics.tsc, -- ts type-checker
  --         nls.builtins.diagnostics.zsh, -- zsh linter (basic compared to shellcheck for bash)
  --       },
  --     }
  --   end,
  -- },

  -- {
  --   'jay-babu/mason-null-ls.nvim',
  --   -- see: https://github.com/jay-babu/mason-null-ls.nvim#primary-source-of-truth-is-null-ls
  --   opts = {
  --     ensure_installed = nil, -- defined in null-ls sources above
  --     automatic_installation = true,
  --     automatic_setup = true,
  --   },
  -- },
}
