 personality = "pragmatic"
 [projects."/Users/michael/Repos/ooloth/dotfiles"]
 trust_level = "trusted"

 [projects."/Users/michael/Repos/ooloth/hub"]
 trust_level = "trusted"

 [tui.model_availability_nux]
 "gpt-5.5" = 3

 [apps.connector_76869538009648d5b282a4bb21c3d157.tools.github_create_issue]
 approval_mode = "approve"

