# see: https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
  linemode = "size"
  scrolloff = 10
  show_hidden = true
  show_symlink = true
  sort_by = "natural"
  sort_dir_first = false
  sort_sensitive = false

# "For users managing network files, it's recommended to disable all previewers and preloaders since
#  previewing and preloading these files means they need to be downloaded locally."
# see: https://yazi-rs.github.io/docs/tips#make-yazi-even-faster
[plugin]
  prepend_preloaders = [
    { mime = "image/*", run = "noop" },
    { mime = "video/*", run = "noop" },
    { name = "*.pdf", run = "noop" },
  ]
  prepend_previewers = [
    { mime = "image/*", run = "noop" },
    { mime = "video/*", run = "noop" },
    { name = "*.pdf", run = "noop" },
  ]
