name: Test Dotfiles Setup Scripts

on:
  # Run on pushes to main branch
  push:
    branches: [ main ]
    paths:
      - 'setup.zsh'
      - 'bin/**'
      - 'lib/**'
      - 'core/**'
      - 'test/**'
      - 'macos/Brewfile'
      - 'config/**'
      - '.github/workflows/test-dotfiles.yml'
  
  # Run on pull requests to main
  pull_request:
    branches: [ main ]
    paths:
      - 'setup.zsh'
      - 'bin/**'
      - 'lib/**'
      - 'core/**'
      - 'test/**'
      - 'macos/Brewfile'
      - 'config/**'
      - '.github/workflows/test-dotfiles.yml'
  
  # Allow manual triggering for debugging
  workflow_dispatch:

jobs:
  test:
    name: Run Dotfiles Tests
    runs-on: macos-latest
    
    # Set default shell to zsh to match our target environment
    defaults:
      run:
        shell: zsh {0}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up environment
        run: |
          # Set DOTFILES environment variable for tests
          echo "DOTFILES=${{ github.workspace }}" >> $GITHUB_ENV
          
          # Ensure zsh is configured properly
          echo "Using zsh version: $ZSH_VERSION"
          echo "Shell: $SHELL"
          
          # Make test runner executable
          chmod +x test/run-tests.zsh
          
      - name: Install shellcheck
        run: |
          # Install shellcheck for static analysis
          brew install shellcheck
          
      - name: Run shellcheck
        run: |
          # Run shellcheck on all bash scripts (.sh and .bash files)
          # Configuration is handled by .shellcheckrc file
          echo "Running shellcheck on bash scripts..."
          
          # Find all bash scripts and run shellcheck
          # Exclude experiment directory which contains intentionally bad examples
          find . \( -name "*.sh" -o -name "*.bash" \) -type f -not -path "./.*" -not -path "./experiment/*" | while read -r file; do
            echo "Checking: $file"
            shellcheck -s bash "$file" || exit 1
          done
          
          echo "✅ All bash scripts passed shellcheck"
          
      - name: Install BATS
        run: |
          # Install BATS for running bash tests
          brew install bats-core
          
      - name: Run BATS test suite
        run: |
          # Run all BATS tests across the repository
          echo "Running BATS tests..."
          
          # Run tests in main test directories
          if [[ -d "test" ]]; then
            echo "Running tests in test/ directory..."
            bats test/**/*.bats
          fi
          
          # Run tests in core/ directories
          if [[ -d "core" ]]; then
            echo "Running tests in core/ directories..."
            find core -name "*.bats" -type f | head -5 | while read -r test_file; do
              echo "Running: $test_file"
              bats "$test_file"
            done
          fi
          
          # Run tests in features/ directories  
          if [[ -d "features" ]]; then
            echo "Running tests in features/ directories..."
            find features -name "*.bats" -type f | head -5 | while read -r test_file; do
              echo "Running: $test_file"
              bats "$test_file"
            done
          fi
          
          echo "✅ All BATS tests completed"
          
      - name: Test symlink verification
        run: |
          echo "Testing symlink creation and verification..."
          ./bin/install/symlinks.bash create
          ./bin/install/symlinks.bash verify
          echo "✅ Symlink verification passed"
          
      - name: Verify BATS test coverage
        run: |
          # Count BATS test files and verify comprehensive coverage
          echo "Verifying BATS test coverage..."
          
          # Count all BATS test files across repository
          TOTAL_BATS=$(find . -name "*.bats" -type f | wc -l | tr -d ' ')
          echo "Total BATS test files found: $TOTAL_BATS"
          
          # Count by directory
          TEST_DIR_BATS=$(find test -name "*.bats" -type f 2>/dev/null | wc -l | tr -d ' ')
          CORE_DIR_BATS=$(find core -name "*.bats" -type f 2>/dev/null | wc -l | tr -d ' ')
          FEATURES_DIR_BATS=$(find features -name "*.bats" -type f 2>/dev/null | wc -l | tr -d ' ')
          
          echo "BATS tests in test/: $TEST_DIR_BATS"
          echo "BATS tests in core/: $CORE_DIR_BATS" 
          echo "BATS tests in features/: $FEATURES_DIR_BATS"
          
          # Verify we found tests in all expected locations
          if [[ $TOTAL_BATS -lt 10 ]]; then
            echo "❌ Warning: Only $TOTAL_BATS BATS tests found, expected more"
            exit 1
          fi
          
          echo "✅ BATS test coverage verification passed"
          
      - name: Test environment validation
        run: |
          # Validate that our test environment works correctly
          echo "Validating test environment..."
          
          # Check that DOTFILES is set correctly
          if [[ -z "$DOTFILES" ]]; then
            echo "❌ DOTFILES environment variable not set"
            exit 1
          fi
          
          echo "✅ DOTFILES set to: $DOTFILES"
          
          # Verify key test directories exist
          if [[ ! -d "$DOTFILES/test" ]]; then
            echo "❌ Test directory not found"
            exit 1
          fi
          
          if [[ ! -f "$DOTFILES/test/run-tests.zsh" ]]; then
            echo "❌ Test runner not found"
            exit 1
          fi
          
          echo "✅ Test infrastructure validated"
          
      - name: Summary
        if: always()
        run: |
          echo "=== Test Summary ==="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Shell: $SHELL"
          echo "ZSH Version: $ZSH_VERSION"
          
          if [[ "${{ job.status }}" == "success" ]]; then
            echo "🎉 All tests passed!"
          else
            echo "❌ Some tests failed. Check the logs above for details."
          fi